/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_aibee_android_location_ByteUtils */

#ifndef _Included_cn_aibee_android_location_ByteUtils
#define _Included_cn_aibee_android_location_ByteUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_aibee_android_location_ByteUtils
 * Method:    getYByte
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_aibee_android_location_ByteUtils_getYByte
  (JNIEnv *, jobject, jbyteArray,jint,jint);

JNIEXPORT jintArray JNICALL Java_cn_aibee_android_location_ByteUtils_rgb24ToPixel
(JNIEnv *, jobject, jbyteArray ,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
